services:
  api:
    build:
      context: .
      dockerfile: ./Backend/Dockerfile
    container_name: api
    ports:
      - "8000:8000"

  web:
    build:
      context: .
      dockerfile: ./Frontend/Dockerfile
    container_name: web
    depends_on:
      - api
    ports:
      - "4173:4173"